#Файл docker-compose.production.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data_production:
  static_volume:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик.   # Это   контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data_production:/var/lib/postgresql/data

# Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    image: grantos1/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    image: grantos1/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

# Добавляем новый контейнер: gateway.
  gateway:
    image: grantos1/taski_gateway
    env_file: .env
    # тут в 15-2-10 неожиданно изчез слеш в конце статикфайлс????
    volumes:
      - static_volume:/staticfiles/
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера.
    ports:
      - 8000:80

